spring:
  application:
    name: native-pdf-annotator
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: postgresql
    show-sql: ${SHOW_SQL:true}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/npa}
    username: ${SPRING_DATASOURCE_USERNAME:npa}
    password: ${SPRING_DATASOURCE_PASSWORD:npa}
    platform: postgresql
    tomcat:
      max-active: ${MAX_ACTIVE_DB_CONNECTIONS:50} # Maximum number of active connections that can be allocated from this pool at the same time.
      max-idle: ${MAX_IDLE_DB_CONNECTIONS:25}
      max-wait: ${MAX_WAIT_DB_CONNECTIONS:10000} # Number of ms to wait before throwing an exception if no connection is available.
      test-on-borrow: ${TEST_ON_BORROW_DB_CONNECTION:true} # Validate the connection before borrowing it from the pool.

  liquibase:
   enabled: ${ENABLE_DB_MIGRATE:true}
   change-log: classpath:/db/changelog/db.changelog-master.yaml

base-urls:
  idam-user: ${IDAM_API_URL:http://localhost:4501}
  idam-s2s: ${S2S_URL:http://localhost:4502}
  s2s-token: ${S2S_TOKEN:AAAAAAAAAAAAAAAA}
  test-url: ${TEST_URL:http://localhost:8080}

management:
  endpoints:
    web:
      base-path: '/'
      exposure:
        include:
         - health
         - info
  health:
    db:
      enabled: true
    disk:
      enabled: true
      threshold: ${HEALTH_DISK_THRESHOLD:262144000}
    status:
     order:
       - FATAL
       - DOWN
       - UNKNOWN
       - UP
  info:
     build:
       enabled: true # Whether to enable build info.
     defaults:
       enabled: true # Whether to enable default info contributors.
     env:
       enabled: true # Whether to enable environment info.
     git:
       enabled: true # Whether to enable git info.
       mode: simple # Mode to use to expose git information.

info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:coh}
    name: ${PACKAGES_NAME:cor}
#    version: ${PACKAGES_VERSION:unknown}

#auth:
#  idam:
#    client:
#      baseUrl: ${IDAM_USER_BASE_URI:http://localhost:4501}
#  provider:
#    service:
#      client:
#        baseUrl: ${S2S_BASE_URI:http://localhost:4502}
#
#
#authorization:
#  idam-roles-whitelist: ${IDAM_ROLES_WHITELIST:solicitor}
#  s2s-names-whitelist: ${S2S_NAMES_WHITELIST:sscs,divorce,ccd,em_gw}
#
info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:coh}
    name: ${PACKAGES_NAME:cor}
#    version: ${PACKAGES_VERSION:unknown}

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:d30268e8-8979-4579-8d58-010dbe03a1e6}

app-insights:
  dev-mode: off
  request-component: on
  telemetry-component: on

deadline:
  extension-days: 7
  # This must be updated in the AAT config too

event-scheduler:
    event-notifier:
      fixed-delay: 10000
    event-trigger:
      fixed-delay: 60000

#
#toggle:
#  includeidamhealth: ${ENABLE_IDAM_HEALTH_CHECK:false}
#  includes2shealth: ${ENABLE_S2S_HEALTH_CHECK:false}
